export const TRADE_EXECUTE = 'TRADE_EXECUTE';
export const AMOUNT_CHANGE = 'AMOUNT_CHANGE';
export const PRICE_UPDATE = 'PRICE_UPDATE';
export const SNACKBAR_CLOSE = 'SNACKBAR_CLOSE';
export const SNACKBAR_OPEN = 'SNACKBAR_OPEN';
export const SELECT_COIN = 'SELECT_COIN';